# Introduction {#intro}

## General Introduction
Phytoplankton are microscopic and free floating aquatic plants, which do not have ability to swim; their movement is supported by water currents [@bryceson]. Phytoplankton; the primary producers of organic matter in aquatic habitats, are equivalent to plants on land [@lugomela1996]. Phytoplankton constitute about 95% of the total marine primary production [@lugomela1996], and serve as the basis for many food webs in the aquatic environment. They are the basis for food for primary consumers such as zooplankton. Secondary and tertiary consumers also feed on these organisms during their larval stage of development [@karlson].

Some phytoplankton species especially those belonging to the cyanobacteria such as Richelia spp, Nostoc spp, and Trichodesmium spp are able to fix free nitrogen and hence enrich marine environment with nitrogenous nutrients [@bryceson; @lugomela2001].  @mcclanahan noted that, nitrogen fixation is among the major source of nitrogen in the near shore waters of Tanzania, and it is highest during the northeast monsoon season when there is minimum mixing of the water column. Under high nutrients concentration, phytoplankton like other microalgae may proliferate to high biomass forming algal blooms commonly known as red tides (Lugomela, 2005). Some phytoplankton species such as Dinophysis spp may cause serious problems even at moderate biomass levels [@devassy]. In most cases red tides have been associated with negative effects, causing severe economic losses to aquaculture, fisheries and tourism operations and having major impacts on environment and human health. 

Phytoplankton growth is dependent upon solar radiation and nutrient substances.   Phytoplankton is essential for other marine life because it is the basis of the food chain [@vargas]. @robinson explained that growth of phytoplankton need carbon dioxide (CO_2_), which absorbed from atmosphere in the seawater. Phytoplankton are also important in ocean carbon cycle; they carry out photosynthesis, which consumes carbon dioxide [@street]. The ocean carbon cycle is highly related to the greenhouse effect and climate change. On a global scale, phytoplankton has important role in earth carbon cycle because it process one billion tonnes of carbon per year [@honjo]. This process of utilizing free carbon dioxide in the water by the marine plants to form organic carbon compounds is called primary production.

Photosynthesis in phytoplankton as is in terrestrial vegetation is dependent upon capturing light energy using chlorophyll pigments and in particular chlorophyll-a (Chl-*a*).  The Chl-*a* absorbs sunlight energy usefully in converting it to sugar during photosynthesis (Raymont, 1980). In aquatic environments, Chl-a concentration is an indicator of phytoplankton abundance and biomass. They can be an effective measure of trophic status and are potential indicator of maximum photosynthetic rate (P-max). 

Abundance and biomass of phytoplankton, as determined via Chl-*a* concentration is important for several planning and management activities of  the coastal waters of the earth [@lillesand; @smits1999quality] because it constitutes key environmental information for many scientific, resource management and policy purposes, as well as for a range of human activities. 

The accurate knowledge of distribution and biomass of phytoplankton as Chl-a, represents the foundation for coastal water classification and management (Dai and Khorram, 1998). Therefore a wide range of scientists and practitioners, including earth observation scientists, fisheries and water managers as well as urban planners seek information on the location, distribution and abundance of Chl-a concentration [@malone1988influences].

Past studies on phytoplankton that have been conducted in Tanzania waters dealt with in situ determination of biomass and abundance of phytoplankton as well as primary production [@lugomela1996; @bryceson; @kyewalyanga]. Other studies examined the photosynthesis-Irradiance (P-I) curve for Trichodesmium spp [@lugomela1996], based on oxygen evolution method, whilst other studies conducted in Zanzibar waters showed interaction between phytoplankton and other aquatic ecosystems [@kyewalyanga2005impact]. The in situ measurement of phytoplankton primary production using 14C has also been conducted in Zanzibar waters [@kyewalyanga].

In most of the previous studies, assessment and identification of phytoplankton distribution at specific areas along the coast of Tanzania waters were dominantly based on the in situ data collection. Although in situ data measurements could be of very high quality, synoptic coverage of the distribution of phytoplankton is not generally achieved. Conversely, Satellite ocean colour data provides large-scale and repetitive coverage sampling of global ocean Chl-a that are necessary to provide better understanding 
of the role of phytoplankton in biogeochemical cycling, climate change, and 
fisheries [@gregg2001global]. 

However, ocean colour data are subjected to several sources of error that affect their accuracy. The sources of error in satellite derived data may be associated with calibration, atmospheric correction, algorithm errors and problems in deriving Chl-a from radiances. Conventional, in situ methods typically provide an acceptable quality and accurate data but can only produce extremely limited spatial observation because of the expenses of sea operations and the large areal extent of the ocean. Thus a combination of the two data sources can maximize the strengths of each data set and produce a high-quality, spatially large data set of ocean Chl-a concentration.
In view of the above, the present study used both in situ measurements and satellite derived ocean colour data for spatial and temporal determination of phytoplankton distribution and abundance in relation to other physico-chemical variables.

##	Statement of the Problem
In marine environment, Chl-a, which is at the base of all food webs, has been used as a proxy indicator of the existence of phytoplankton (Babin et al., 1996). The spatial and temporal distribution and abundance of phytoplankton is important for aquatic ecosystems, particularly, the fisheries sector. In Tanzania there are limited studies on temporal and spatial distribution and abundance of phytoplankton. Outstanding studies include the study of @bryceson dealt with the ecology of phytoplankton in Dar es Salaam and that of [@lugomela1996] that dealt with the taxonomy as well as the seasonal and spatial abundance of phytoplankton in Zanzibar near shore waters.

Due to limited information on the distribution and abundance of phytoplankton, it is costly for fishers in terms of time and money, to locate fishing. Also fisheries managers and policy makers fail to develop good management strategies and policies due to unreliable and lack of timely information on the location of potential fishing grounds. Knowing the spatial and temporal abundance of phytoplankton will help fishers and fisheries managers to identify locations of high fish catch and their seasonal variation. This in turn will assist policy and decision makers on formulating policies for management of the marine fisheries in Tanzania. 

Historically, phytoplankton biomass has been determined using in situ method which has been shown to produce high quality data of phytoplankton biomass, but with limited details on temporal and spatial variability [@babin]. The use of Remote Sensing and Geographic Information System (GIS) has recently proved to be an effective and efficient technique for studying phytoplankton in coastal and marine environment [@frouin1996spectral]. Despite the usefulness of this approach (due to its repetitive coverage of the satellites) at short time intervals [@frouin1996spectral], its application on the coastal and marine waters of Tanzania is very scant. Thus, to try to narrow this gap, the present study applied both in situ collected and remotely-sensed satellite data to determine distribution and abundance of phytoplankton along the Pemba and Zanzibar channels. 

##	Objectives of the Research
The main objective of the present study was to determine the spatial and temporal variation of phytoplankton distribution and abundance in relation to other physico-chemical variables using remotely sensed satellite and in situ data along Zanzibar and Pemba channels.

###	Specific Objectives
The specific objectives of the study were to;

+ Determine temporal and spatial variation of phytoplankton distribution and abundance using satellite and in situ chlorophyll-a concentration.
+ Examine the influence of physico-chemical variables (SST, nitrate, phosphate, dissolved oxygen, salinity and pH) on the distribution and abundance of phytoplankton. 
+ Compare the chlorophyll-a concentration between satellite delivered and in situ collected data.

##	Research Questions	
This study tried to answer the following questions:

+ Is there any significant temporal and spatial variation of phytoplankton distribution and abundance in the investigated study sites?
+ What is the influence of physico-chemical variables on the distribution and abundance of phytoplankton? + What is the relationship between satellite chlorophyll-a measurements and in situ chlorophyll-a concentration?

