# Conclusion and Recommendation

This study was conducted to determine the spatial and temporal distribution and abundance of phytoplankton in the Zanzibar and Pemba channels using both satellite and in situ Chl-a measurements. The results of the study revealed that, there was a spatial and temporal variation of phytoplankton distribution and abundance, with Zanzibar having relatively higher Chl-a concentration than the Pemba channel.

The results of the present study revealed that Chl-a concentration at both Zanzibar and Pemba channels varied on seasonal basis with relatively higher concentration during the rainy season as compared to the dry season. The higher concentration of Chl-a during the rainy season was associated with the increased level of nutrients derived from the land based sources as most of the rainfall at both sites was received during this season. Analyses of the environmental variables which influenced the Chl-a concentration at the investigated sites revealed that during the dry season, the Chl-a concentration was mostly influenced by both nitrate and phosphate nutrients, but during the rainy season the Chl-a concentration was mostly influenced by nitrate and salinity. More than 50% of these variables accounted for the variation of Chl-a concentration.

To the best of my knowledge, the present study was the first case study done in Tanzanian waters using the remotely sensed satellite Chl-a together with the in situ fluorometric Chl-a in the determination of the phytoplankton distribution and abundance. The results showed that, there was a strong positive correlation between satellite and in situ Chl-a concentration in both dry and rainy seasons. However the satellite tended to over-estimate the Chl-a values. This may be avoided by applying appropriate algorithm during the processing of the satellite data especially to coastal (Case II) waters; this will help to differentiate between the Chl-a and other water components such as CDOM and suspended sediments which might  be the major factors for the higher Chl-a values. Employing the suggested algorithm will not only make it possible for distinguishing between Chl-a and other water components but also will make the process of cloud correction easier and improve the data quality (by reducing the number of cells with no data). Finally, future studies should consider employing higher spatial resolution remote sensing data (such as MERIS) than the one used in this study in order to have a better match up analysis between in situ and satellite and good spatial pattern of the phytoplankton at a given area.

The in situ data collected for the Pemba channel site were done proximal to the Pangani estuary and no data of upstream the river were collected in this study due to financial and time limitation. More studies should be conducted to include the water of upstream to downstream the river in order to determine the phytoplankton variation at different water salinity. 
